# Generated by Django 3.2.3 on 2021-08-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.IntegerField()),
                ('subject', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=122)),
                ('description', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=512)),
                ('date', models.DateField()),
            ],
        ),
    ]
