# Generated by Django 3.2.3 on 2021-08-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_study_material_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice_Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_class', models.IntegerField()),
                ('subject', models.CharField(max_length=122)),
                ('title', models.CharField(max_length=122)),
                ('description', models.TextField()),
                ('questions', models.JSONField()),
                ('date', models.DateField()),
            ],
        ),
    ]
