# Generated by Django 3.2.3 on 2021-08-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210818_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doubts',
            new_name='Doubt',
        ),
    ]
